//Khởi tạo danh sách sản phẩm
function createProduct(){
    if (localStorage.getItem('products') == null) {
        let products = [{
            id: 1,
            status: 1,
            title: 'Hạt Today Dinner dành cho chó trưởng thành',
            img: './assets/image/products/today-dinner.webp',
            category: 'Đồ ăn khô cho chó',
            price: 300000,
            desc: 'Hạt thức ăn Today Dinner được nghiên cứu dựa trên công thức cân bằng giá trị dinh dưỡng giúp duy trì chế độ ăn lành mạnh cho thú cưng.'
        },
        {
            id: 2,
            status: 1,
            title: 'Hạt Today Dinner dành cho chó con',
            img: './assets/image/products/today-dinner-1.webp',
            category: 'Đồ ăn khô cho chó',
            price: 290000,
            desc: 'Công thức định lượng các chất theo tỷ lệ phù hợp, để mỗi bữa ăn của cún luôn đầy đủ và cân bằng chất dinh dưỡng.'
        },
        {
            id: 3,
            status: 1,
            title: 'Hạt Keos+ hỗ trợ tiêu hóa cho chó, vị thịt cừu&gạo',
            img: './assets/image/products/keos+.png',
            category: 'Đồ ăn khô cho chó',
            price: 35000,
            desc: 'Các bé cún rất thường gặp phải vấn đềvề tiêu hóa nên việc bổ sung dinh dưỡng hợp lý để giúp các bé có một hệ tiêu hóa khỏe mạnh. Vì vậy, với công thức Natural Shield, Keos+ sẽ giúp cải thiện hệ tiêu hóa, chất lượng phân và sức khỏe ổn định lâu dài cho bé cún.'
        },
        {
            id: 4,
            status: 1,
            title: 'Hạt Keos+ cho chó trưởng thành vị gà&rau củ',
            img: './assets/image/products/keos+-1.png',
            category: 'Đồ ăn khô cho chó',
            price: 35000,
            desc: 'Keos+ vị rau gà&rau củ giúp giảm mùi hôi phân nhờ chiếc xuất cây Yucca, dễ hấp thu dinh dưỡng và tiêu hóa. Bổ sung omega 3,6 giúp lông bóng mượt đồng thời răng cũng ít xuất hiện mảng bám.'
        },
        {
            id: 5,
            status: 1,
            title: 'Hạt Keos+ cho chó con, vị sữa, gà&trứng',
            img: './assets/image/products/keos+-2.png',
            category: 'Đồ ăn khô cho chó',
            price: 35000,
            desc: 'Vị sữa, gà&trứng dành cho chó con bổ sung DHA&Choline giúp phát triển trí não, tăng cường miễn dịch với các loại vitamin. Bổ sung omega 3,6 giúp lông bóng mượt đồng thời răng ít xuất hiện mảng bám.'
        },
        {
            id: 6,
            status: 1, 
            title: 'Hạt Pedigree cho chó con 2.7kg, vị gà, trứng&sữa',
            img: './assets/image/products/pedigree-1.png',
            category: 'Đồ ăn khô cho chó',
            price: 210000,
            desc: 'Tăng cường phát triển não bộ, Pedigree cho chó con chưa các chất dinh dưỡng quan trọng như DHA, chất xơ và canxi giúp phát triển tối ưu trí não của bé cún ngoài ra hạt Pedigree còn chứa chất xơ hỗ trợ hệ tiêu hóa và sức khỏe tổng thể cho bé. Tăng cường sức khỏe răng&xương, nuôi dưỡng da khỏe&lông bóng mượt.'
        },
        {
            id: 7,
            status: 1,
            title: 'Thức ăn Pedigree cho các bé trưởng thành giống mini 1.3kg, vị bò, cừu&rau củ',
            img: './assets/image/products/pedigree-2.png',
            category: 'Đồ ăn khô cho chó',
            price: 103000,
            desc: 'Giàu protein chất lượng cao, bổ sung omega 6&kẽm, chất xơ tự nhiên giúp hệ tiêu hóa khỏe mạnh.'
        },
        {
            id: 8,
            status: 1,
            title: 'Thức ăn cho chó lớn SmartHeart vị bò nướng gói 3kg',
            img: './assets/image/products/smartheart.png',
            category: 'Đồ ăn khô cho chó',
            price: 180000,
            desc: 'Kích thước hạt nhỏ phù hợp với lực cắn của cún, giảm gây tổn hại cho răng, vitamin e và selenium tăng cường miễn dịch. Hàm lượng omgega3&6 cân bằng giúp trái tim khỏe mạnh và da lông khỏe đẹp.'
        },
        {
            id: 9,
            status: 1,
            title: 'Thức ăn cho chó SmartHeart vị bò&sữa gói 3kg',
            img: './assets/image/products/smartheart-1.png',
            category: 'Đồ ăn khô cho chó',
            price: 110000,
            desc: 'Hàm lượng đạm 26% giúp cún phát triển toàn diện, canxi&photpho cân bằng nhanh chóng phát triển khung xương cho cúnvitamin e và selenium tăng cường miễn dịch. Hàm lượng omgega3&6 dồi dào từ dầu cá giúp trái tim khỏe mạnh .',
        },
        {
            id: 10,
            status: 1,
            title: 'Pate cho chó MONGE vị thịt cá hồi hộp 400gr',
            img: './assets/image/products/pate.png',
            category: 'Đồ ăn vặt&Pate',
            price: 50000,
            desc: 'Pate Monge cho chó Bwild Grain Free Formul là thức ăn cho chó hoàn chỉnh và cân bằng dành cho chó trưởng thành. Được phát triển đặc biệt để chăm sóc sức khỏe cho những chú chó của bạn thông qua tuyển chọn các nguồn carbohydrate phái sinh phi ngũ cốc thay thế như bí xanh và bí ngô. Công thức được tăng cường với xylo-oligosacarit (XOS), prebiotic thế hệ tiếp theo để hỗ trợ sức khỏe đường ruột. Công thức này hỗ trợ xương khớp do có chứa glucosamine và chon-droitin sulphate.',
        },
        {
            id: 11,
            status: 1,
            title: 'Thức ăn H1 cho chuột Hamster nhỏ, lớn, mang thai hãng Bucatstate 520gr',
            img: './assets/image/products/h1.png',
            category: 'Đồ ăn khô cho chuột',
            price: 150000,
            desc: 'Phù hợp với đa dạng loại Hamster: Hamster Bear, Hamster Winter White, Hamster Robo, Hamster Campell, Hamster Nga.Thực phẩm giàu Protein: Bổ sung các loại đạm động vật dễ hấp thu phù hợp với chuột bầu khi bổ sung năng lượng, tăng sữa, cũng như có tác dụng vỗ béo cho những mẹ bầu gầy ốm.Bổ sung canxi & photpho chế độ sinh dưỡng toàn diện. Các chất dinh dưỡng đa dạng độc đáo giúp dễ dàng tiêu hóa và hấp thụ, giúp cho quá trình trao đổi chất hiệu quả hơn.Hạt ngũ cốc trái cây:  Bổ sung cỏ nén mài răng, tăng cường sức khỏe răng miệng.',
        },
        {
            id: 12,
            status: 1,
            title: 'Thức ăn Nutrience cho chó vị bò,cừu hạt to gói 500g',
            img: './assets/image/products/nutrience.png',
            category: 'Đồ ăn khô cho chó',
            price: 180000,
            desc: 'Thức ăn cho chó Nutrience SubZero Prairie Red được sản xuất tại Canada, sử dụng nguồn nguyên liệu tươi sạch từ bò, lợn, lợn rừng của vùng Alberta và cá đánh bắt tự nhiên từ bờ biển Thái Bình DươngHạt khô giàu đạm được kết hợp với hạt sấy thăng hoa Nutriboost là khối thịt bò sống được sấy thăng hoa (giữ trọn dưỡng chất và hương vị tự nhiên), đồng thời được bổ sung vẹm xanh giúp hỗ trợ khớp, bí đỏ giúp tốt cho tiêu hóa, dầu gan cá tuyết giàu omega-3 và tảo biển Acadian giúp tăng cường miễn dịch.',
        },
        {
            id: 13,
            status: 1,
            title: 'Thức ăn Nutrience cho chó giống nhỏ vị gà, cá hồi&rau gói 500g',
            img: './assets/image/products/nutrience-1.png',
            category: 'Đồ ăn khô cho chó',
            price: 175000,
            desc: 'Giàu protein:Tất cả nguyên liệu như thịt bò, heo rừng, bò tót bison và cá biển đại dương Canada đều được cung cấp tươi sống không qua bảo quản đông lạnh.Trái cây và rau củ quả tươi xanh có chứa hàm lượng rất cao các chất chống oxi hóa và đặc tính dinh dưỡng thực vật.',
        },
        {
            id: 14,
            status: 1,
            title: 'Thức ăn SmartHeart cho chó lớn vị gà&trứng gói 3kg',
            img: './assets/image/products/smartheart-2.png',
            category: 'Đồ ăn khô cho chó',
            price: 192000,
            desc: 'Đây là dòng thức ăn hạt dành cho chó trưởng thành (trên 12 tháng tuổi) giống vừa và lớn (từ 10 đến trên 25kg) với hương vị mới là vị gà và trứng, giúp bữa ăn của cún đa dạng hơn. Sản phẩm chứa thành phần trứng nguyên quả sấy khô, là nguồn protein dễ hấp thu nhất Sản phẩm đảm bảo cung cấp nguồn dinh dưỡng cân bằng & hoàn chỉnh đạt tiêu chuẩn AAFCO, bổ sung nhiều dưỡng chất thiết yếu giúp bảo vệ sức khỏe toàn diện cho cún cưng.',
        },
        {
            id: 15,
            status: 1,
            title: 'Thức ăn SmartHeart cho chó trưởng thành giống nhỏ vị bò nướng gói 2,7kg',
            img: './assets/image/products/smartheart-3.png',
            category: 'Đồ ăn khô cho chó',
            price: 150000,
            desc: 'Thức ăn SmartHeart dành cho chó trưởng thành giống nhỏ vị bò nướng sử dụng các thành phần chất lượng giúp bổ sung dầu cá (giàu DHA và axit béo Omega3) và Lecithin (giàu Choline), tăng cường chức năng não và hệ thần kinh và thúc đẩy sức khỏe tim mạch. Sản phẩm có kết cấu hạt giòn đặc biệt giúp giảm mảng bám trên răng.',
        },
        {
            id: 16,
            status: 1,
            title: 'Hạt Whiskas cho mèo trưởng thành vị cá biển 3kg',
            img: './assets/image/products/whiskas.png',
            category: 'Đồ ăn khô cho mèo',
            price: 250000,
            desc: 'Mèo là loài động vật có bản tính săn mồi nhanh nhạy nên cơ thể chúng rất cần được chú ý bổ sung các chất dinh dưỡng cần thiết để  luôn lanh lợi và khỏe mạnh. Sản phẩm thức ăn hạt khô cho mèo con Whiskas sẽ cung cấp cho mèo những lợi ích tốt.Hương vị Cá Biển và Sữa thơm ngon với vỏ ngoài giòn tan thơm vị cá, nhân sữa bên trong mềm mại và béo ngậy đảm bảo chất lượng cho mỗi bữa ăn của mèo.Cung cấp đủ vitamin và taurine, giúp đôi mắt của mèo luôn sáng tinh anh và khỏe mạnh. Bổ sung dưỡng chất đạm, Vitamin và khoáng chất từ cá tươi tốt cho hệ phát triển tối ưu, giúp mèo có cơ thể năng động và tràn đầy sức sống. Sản phẩm giàu Omega 3&6, axit béo và kẽm giúp mèo có bộ lông khỏe, mềm mại và bóng mượt.',
        },
        {
            id: 17,
            status: 1,
            title: 'Hạt Whiskas cho mèo trưởng thành vị cá ngừ 1,2kg',
            img: './assets/image/products/whiskas-1.png',
            category: 'Đồ ăn khô cho mèo',
            price: 125000,
            desc: 'Thức ăn cho mèo WHISKAS đã được chế biến đặc biệt với chất chống oxy hóa để hỗ trợ nhu cầu dinh dưỡng của mèo, tăng cường sức khỏe toàn diện.hạt gồm axit béo omega 6 và kẽm, mang đến cho người bạn mèo của bạn một bộ lông bóng mượt tuyệt đẹp.Được bổ sung vitamin A và taurine, thức ăn cho mèo lớn WHISKAS dạng hạt của chúng tôi hỗ trợ thị lực của mèo để chúng có thể nắm bắt mọi cơ hội vui chơi.',
        },
        {
            id: 18,
            status: 1,
            title: 'Thức ăn cho mèo con Whiskas vị cá ngừ dạng túi 80g',
            img: './assets/image/products/whiskas-2.png',
            category: 'Đồ ăn khô cho mèo',
            price: 45000,
            desc: 'Sản phẩm cung cấp dinh dưỡng hoàn hảo, giúp những chú mèo của bạn có thể phát triển một cách toàn diện. Sản phẩm có chứa độ béo và khoáng chất tối đa giúp nuôi dưỡng những bộ lông mềm mượt, bên cạnh đó các thành phần rất dễ tiêu hóa cho nên chất dinh dưỡng sẽ được hấp thu một cách nhanh chóng.Vị cá ngừ thơm ngon sẽ kích thích vị giác của cún, giúp chúng ngon miệng hơn và sẽ tiêu thụ thức ăn một cách dễ dàngCác vitamin giúp tăng cường hệ miễn dịch cho mèo, nhằm loại bỏ một số bệnh về da, lông, tiểu đường, béo phì.',
        },
        {
            id: 19,
            status: 1,
            title: 'Thức ăn cho mèo con Whiskas vị gà dạng sốt túi 70g',
            img: './assets/image/products/whiskas-3.png',
            category: 'Đồ ăn khô cho mèo',
            price: 40000,
            desc: 'Thức ăn dạng sốt cho mèo WHISKAS là nguồn dinh dưỡng cân bằng và hoàn thiện dành cho mèo con, đảm bảo tối ưu sức khỏe và tinh thần cho chúng. Được chế biến từ những nguyên liệu chất lượng cao, bao gồm cả gà thật, thức ăn dạng sốt cho mèo của chúng tôi mang đến dinh dưỡng và hương vị đặc biệt cho chú mèo của bạn.',
        },
        {
            id: 20,
            status: 1,
            title: 'Thức ăn hạt Catsrang Lna Hàn Quốc dành cho mèo mọi lứa tuổi gói 5kg',
            img: './assets/image/products/catstrang.png',
            category: 'Đồ ăn khô cho mèo',
            price: 550000,
            desc:'Hạt Catsrang giúp mèo đi phân rắn và giảm thiểu mùi hôi khó chịu,ngăn ngừa lông vón cục trong ruột mèo.Hàm lượng dinh dưỡng cân bằng, catsrang phù hợp trong việc cải thiện da lông, phòng tránh bệnh quáng gà ở mèo. Sử dụng protein cao cấp tốt cho hệ tiêu hóa,đáp ứng tiêu chí 6 không: không chất bảo quản,  không chất kháng sinh, không chất tạo mùi, không chất tạo màu, không hương liệu nhân tạo, không chất chống mốc.',      
        },
        {
            id: 21,
            status: 1,
            title: 'Hạt N&D cao cấp cho mèo con vị gà&lựu gói 500g',
            img: './assets/image/products/N&D.png',
            category: 'Đồ ăn khô cho mèo',
            price: 150000,
            desc: 'Hạt N&D là một loại hạt mới nhưng thường xuyên được các trại mèo uy tín ở Việt Nam sử dụng 98% đạm có nguồn gốc từ thịt bột thịt. Không có chất bảo quản nhân tạo. Không độn ngũ cốc. Hạt được đánh giá khá cao so với các hạt tầm giá trên thị trường .',
        },
        {
            id: 22,
            status: 1,
            title: 'Hạt N&D cao cấp cho mèo trưởng thành vị cá,cam&bí đỏ gói 1kg',
            img: './assets/image/products/N&D-1.png',
            category: 'Đồ ăn khô cho mèo',
            price: 300000,
            desc: 'Hạt N&D là một loại hạt mới nhưng thường xuyên được các trại mèo uy tín ở Việt Nam sử dụng 98% đạm có nguồn gốc từ thịt bột thịt. Không có chất bảo quản nhân tạo. Không độn ngũ cốc. Hạt được đánh giá khá cao so với các hạt tầm giá trên thị trường .',
        },
        {
            id: 23,
            status: 1,
            title: 'Hạt Mr.Vet cho mọi loại mèo gói 1kg',
            img: './assets/image/products/mr-vet.png',
            category: 'Đồ ăn khô cho mèo',
            price: 250000,
            desc: 'Dòng hạt hoslistic cao cấp, với công thức dành riêng cho mèo được nuôi trong nhà, kiểm soát mùi hôi chất thải nhờ chiết xuất từ cây yucca, giảm búi lông và tiêu hóa khỏe nhờ công thức 6 hương vị cá tươi nguyên chất, duy trì thể trạng lý tưởng cho mèo ít vận động. Ít hoặc không có chất phụ gia và chất bảo quản nhân tạo, đảm bảo an toàn cho mèo.Phù hợp cho mèo ở mọi lứa tuổi bao gồm mèo con, mèo trưởng thành và mèo mang thai .',
        },
        {
            id: 24,
            status: 1,
            title: 'Hạt Me-O cho mèo vị cá ngừ gói 3kg',
            img: './assets/image/products/me-o.png',
            category: 'Đồ ăn khô cho mèo',
            price: 290000,
            desc: 'Thức ăn Me-O hương vị cá ngừ dành cho mèo trưởng thành từ 12 tháng trở lên. Với nguyên liệu chủ yếu từ cá có hàm lượng dinh dưỡng đầy đủ và cân bằng giúp cung cấp đầy đủ dưỡng chất cho mèo trưởng thành., phòng ngùa bệnh tật , đảm bảo sự phát triển khỏe mạnh. Đặc biệt với công thức Flutd giúp ngăn ngừa bệnh đường tiết niệu và sỏi bàng quang, hỗ trợ cho mèo của bạn có được sức khoẻ tốt và sự nhanh nhạy.',
        },
        {
            id: 25,
            status: 1,
            title: 'Thức ăn R&M cho chuột Hamster gói 900g',
            img: './assets/image/products/R&M.png',
            category: 'Đồ ăn khô cho chuột',
            price: 159000,
            desc: 'Thức ăn hãng R&M cho chuột hamster Bear Syrian  ngũ cốc bổ sung trái cây rau củ thảo mộc, Đồ ăn cho sóc giàu dinh dưỡng.',
        },
        {
            id: 26,
            status: 1,
            title: 'Thức ăn SmartHeart cho chuột lang gói 3kg',
            img: './assets/image/products/smartheart-4.png',
            category: 'Đồ ăn khô cho chuột',
            price: 206000,
            desc: 'Dinh dưỡng cân bằng và hoàn chỉnh cho chuột lang mọi giai đoạn.Bổ sung nhiều loại Vitamin hỗ trợ phát triển, đặc biệt là Vitamin C.',
        },
        {
            id: 27,
            status: 1,
            title: 'Cỏ Alfala Oxbow dành cho chuột lang',
            img: './assets/image/products/co-alfalfa.png',
            category: 'Đồ ăn khô cho chuột',
            price: 350000,
            desc: 'Cỏ Alfalfa Oxbow vị ngọt, mềm là một loại cỏ khô đạt tiêu chuẩn Organic thuộc họ đậu, chứa nhiều chất xơ, protein và năng lượng tốt cho hệ tiêu hóa cho các dòng thú cưng như: thỏ cảnh, chuột lang, Chinchilla. Cỏ Alfalfa là loại cỏ tốt cho thú cưng đang phát triển, đang mang thai hoặc cho con bú.',
        },
        {
            id: 28,
            status: 1,
            title: 'xương gặm canxi sạch răng cho chó vị sữa - thơm miệng cho chó mèo',
            img: './assets/image/products/xuong-gam.png',
            category: 'Đồ ăn vặt&Pate',
            price: 250000,
            desc: 'Món snack bổ sung canxi, giúp chắc răng thơm miệng, làm sạch trắng răng và lợi, giảm cao răng tích tụ..',
        },
        {
            id: 29,
            status: 1,
            title: 'Soup thưởng cho mèo',
            img: './assets/image/products/soup.png',
            category: 'Đồ ăn vặt&Pate',
            price: 10000,
            desc: 'Kích thích sự thèm ăn.Dạng soup dễ tiêu hóa và hấp thụ.Giàu taurine và chất dinh dưỡng khác giúp mắt mèo sáng hơn,lông bóng mượt hơn.',
        },
        {
            id: 30,
            status: 1,
            title: 'Pate cho mèo vị cá ngừ&cá biển 400g',
            img: './assets/image/products/pate-1.png',
            category: 'Đồ ăn vặt&Pate',
            price: 90000,
            desc: 'Pate Monge Special Cat là dòng thức ăn ướt cao cấp dành cho mèo của thương hiệu Monge (Ý), nổi bật với các thành phần tự nhiên như thịt và cá tươi, cung cấp protein và dinh dưỡng cân đối cho mèo. Sản phẩm có nhiều hương vị phong phú, kết cấu mềm mịn dễ ăn, không chứa chất tạo màu, giúp tăng cường sức khỏe, hấp dẫn vị giác và trải nghiệm ăn uống cho mèo.',
        },
        {
            id: 31,
            status: 1,
            title: 'Cây thịt bò cho chó 500g - Snack dẻo thịt tươi tự nhiên, thơm ngon',
            img: './assets/image/products/cay-thit-bo.png',
            category: 'Đồ ăn vặt&Pate',
            price: 50000,
            desc: 'Thành phần 100% thịt bò tươi không chất bảo quản, không phẩm màu độc hại.Thịt dẻo dài, thơm lừng, giúp kích thích vị giác của boss, hỗ trợ làm sạch răng.Giúp bổ sung năng lượng, hỗ trợ tiêu hóa và tăng sức đề kháng.',
        },
        {
            id: 32,
            status: 1,
            title: 'Pate Monge cho chó vị gà&rau củ 100gr',
            img: './assets/image/products/pate-2.png',
            category: 'Đồ ăn vặt&Pate',
            price: 50000,
            desc: 'Pate Monge 100g là sản phẩm nổi bật đến từ thương hiệu Monge danh tiếng của Ý. Với hương vị hấp dẫn từ các loại thịt cao cấp như gà, gà tây, cá ngừ dòng pate này được yêu thích rộng rãi tại Châu Âu nhờ chất lượng vượt trội và độ an toàn cao. Sản phẩm không chứa gluten một tác nhân dễ gây dị ứng nên hoàn toàn phù hợp cho cả những chú chó có hệ tiêu hoá nhạy cảm.',
        },
        {
            id: 33,
            status: 1,
            title: 'Balo Luna vận chuyển chó mèo, thoáng mát cho thú cưng',
            img: './assets/image/products/balo.png',
            category: 'Phụ kiện',
            price: 139000,
            desc: 'Ba Lô Vận Chuyển dùng để đựng / xách vật nuôi khi ra đường, đi chơi rất tiện lợi, an toàn và tạo cảm giác thoải mái cho vật nuôi.',
        },
        {
            id: 34,
            status: 1,
            title: 'Vòng cổ HiPiDog cho chó mèo nhỏ',
            img: './assets/image/products/vong-co.png',
            category: 'Phụ kiện',
            price: 40000,
            desc: 'Lớp bên trong cổ áo ôm sát vị trí cổ, bọt polypropylene mềm đặc biệt, bảo vệ cổ và lông của chó.  Thích hợp cho các mùa: Tất cả các mùa.',
        },
        {
            id: 35,
            status: 1,
            title: 'Đệm ổ nằm dành cho chuột hamster',
            img: './assets/image/products/dem.png',
            category: 'Phụ kiện',
            price: 45000,
            desc: 'Đi kèm với không gian rộng và thiết kế ba chiều, ổi thú cưng này siêu mềm, thân thiện với da, chống mài mòn, thoải mái cho thú cưng của bạn khi ngủ và không dễ bị biến dạng. Với đặc điểm là họa tiết hoạt hình dễ thương và thiết kế nửa kín, chiếc tổ thú cưng rất dễ thương, hấp dẫn, bền đẹp và có thể giặt được cũng như có thể trang trí cho ngôi nhà của bạn và rất dễ dàng vệ sinh.',
        },
        {
            id: 36,
            status: 1,
            title: 'Túi du lịch đựng hamster, chuột lang',
            img: './assets/image/products/balo-1.png',
            category: 'Phụ kiện',
            price: 200000,
            desc: 'Túi đựng động vật nhỏ đi du lịch: Túi đựng chuột lang này thích hợp cho các vật nuôi nhỏ như chuột đồng, chuột lang, thỏ, vẹt, v.v., là sự lựa chọn lý tưởng cho bạn khi đi du lịch.Dây đeo vai có thể tháo rời: Túi đựng thú cưng này có thể được sử dụng như một túi xách hoặc một túi đeo chéo, dây đeo vai có thể tháo rời cho phép bạn sử dụng linh hoạt trong các trường hợp khác nhau.',
        },
        ]
        localStorage.setItem('products', JSON.stringify(products));
    }
}
// Create admin account 
function createAdminAccount() {
    let accounts = localStorage.getItem("accounts");
    if (!accounts) {
        accounts = [];
        accounts.push({
            fullname: "Trương Đỗ Thùy Ngân",
            phone: "thuyngan",
            password: "14092311",
            address: 'https://github.com/nganthuydotruong',
            email: 'nganthuydotruong@gmail.com',
            status: 1,
            join: new Date(),
            cart: [],
            userType: 1
        })
        localStorage.setItem('accounts', JSON.stringify(accounts));
    }
}    
window.onload = createProduct();
window.onload = createAdminAccount();
